fields:
  pCYP:
    name: "Допуски ВВС"
    items:
      - name: "Транспортные вертолёты"
      - name: "Боевые вертолёты"
      - name: "Транспортные самолёты"
      - name: "Боевые самолёты"

  pBTV:
    name: "Допуски для бронетехники"
    items:
      - name: "Легкая гусеничная техника"
      - name: "Средняя гусеничная техника"
      - name: "Тяжелая гусеничная техника"
      - name: "Артиллерия"

  pRP:
    name: "РП стороны"
    items:
      - name: "Зевс"
      - name: "Легионер (повстанец)"
      - name: "Стрингеры"
      - name: "Красный крест"
      - name: "НАТО"
      - name: "Легионер"

  pKMB:
    name: "Инструкторский состав"
    items:
      - name: "Лётчиков"
      - name: "Танкистов"
      - name: "РП сторон"
      - name: "КМБ"
      - name: "Офицеров"
      - name: "Снайперов"
      - name: "Инженеров"
      - name: "Медиков"

  pSkill:
    name: "Курсы"
    items:
      - name: "Офицер"
      - name: "Инженер"
      - name: "Снайпер"
      - name: "Медик"
      - name: "Голубой Берет"
      - name: "ССО"

  pExp:
    name: "Опыт"
    range: [-10000, 10000]

  pKarma:
    type: "fixed"
    name: "Штрафник"

  pLvl:
    type: "fixed"
    name: "Уровень"
    range: [0, 14]

  pTitle:
    type: "string"
    name: "Надпись над ником"

  pUnits:
    type: "fixed"
    name: "Отряд"

  pAdmin:
    name: "Админ"
    items:
      - name: ""
      - name: "Военная полиция"

  playerInfo:
    type: "player_info"
    name: "Информация об игроке"
    